# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19T0cYRODK35fPizPcvZ7-dAtCORwXZ3G
"""

m = int(input("Please enter a number : "))
p=[]
for n in range(2, m):
    for k in range(2, m):
        if n % k == 0 and n != k:
            break
        else:
            for t in p:
                if  n % t == 0:
                    break
            else:
                p.append(n)

print (p)